# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_auto_20180524_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isCheck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='isOrder',
            field=models.BooleanField(default=True),
        ),
    ]
